spring:
  application:
    name: nbbang-party, common     # common 공통 프로퍼티 불러오기
  profiles:
    active: prod
  config:
    import: optional:configserver:http://129.154.222.27:8197
  rabbitmq:
    host: 129.154.222.27
    port: 5672
    username: nbbang
    password: nbbang-dev!@#
  main:
    allow-bean-definition-overriding: true

# 서버 설정
server:
  port: 9200
  servlet:
    context-path: /nbbang-party

# acutator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

# 키스토어 복호화
encrypt:
  key-store:
    location: file:///home/ubuntu/nbbang/key/nbbang-config.jks
    password: config-access
    alias: nbbang-config-key
